baseURL = "http://example.com/"
languageCode = "en-us"
title = "Pengumuman Panitia FIM 21"
theme = "hugograyscale"
#googleAnalytics = ""
[params]
    # Provide some metadata for search and indexing services
    description = "Pengumuman Panitia FIM 21"
    author = "FIM Engineering"
